
name: ios-mcn-build


on:
  push:
    tags:
      - 'n5.*'
      - 'n6.*'

env:
  REGISTRY: ghcr.io
  DOCKER_REGISTRY: ghcr.io/
  DOCKER_REPOSITORY: jeena-reji/docker-build

jobs:
  authcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

  n5-base:
    needs: authcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          if [[ $TAG_NAME == n6.* ]]; then
            echo "SUFFIX=-uni" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n6-}" >> $GITHUB_ENV
          elif [[ $TAG_NAME == n5.* ]]; then
            echo "SUFFIX=" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n5-}" >> $GITHUB_ENV
          else
            echo "Unsupported tag format: $TAG_NAME"
            exit 1
          fi

      - name: Build and Push base image
        run: |
          docker build -t $DOCKER_REGISTRY$DOCKER_REPOSITORY/ran-base${SUFFIX}:${VERSION} .
          docker push $DOCKER_REGISTRY$DOCKER_REPOSITORY/ran-base${SUFFIX}:${VERSION}

  n5-build:
    needs: n5-base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          if [[ $TAG_NAME == n6.* ]]; then
            echo "SUFFIX=-uni" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n6-}" >> $GITHUB_ENV
          elif [[ $TAG_NAME == n5.* ]]; then
            echo "SUFFIX=" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n5-}" >> $GITHUB_ENV
          else
            echo "Unsupported tag format: $TAG_NAME"
            exit 1
          fi

      - name: Build and Push build image
        run: |
          docker build -t $DOCKER_REGISTRY$DOCKER_REPOSITORY/ran-build${SUFFIX}:${VERSION} .
          docker push $DOCKER_REGISTRY$DOCKER_REPOSITORY/ran-build${SUFFIX}:${VERSION}

  n5-gnb:
    needs: n5-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          if [[ $TAG_NAME == n6.* ]]; then
            echo "SUFFIX=-uni" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n6-}" >> $GITHUB_ENV
          elif [[ $TAG_NAME == n5.* ]]; then
            echo "SUFFIX=" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n5-}" >> $GITHUB_ENV
          else
            echo "Unsupported tag format: $TAG_NAME"
            exit 1
          fi

      - name: Build and Push gnb image
        run: |
          docker build -t $DOCKER_REGISTRY$DOCKER_REPOSITORY/n5-gnb${SUFFIX}:${VERSION} .
          docker push $DOCKER_REGISTRY$DOCKER_REPOSITORY/n5-gnb${SUFFIX}:${VERSION}

  n5-cuup:
    needs: n5-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          if [[ $TAG_NAME == n6.* ]]; then
            echo "SUFFIX=-uni" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n6-}" >> $GITHUB_ENV
          elif [[ $TAG_NAME == n5.* ]]; then
            echo "SUFFIX=" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n5-}" >> $GITHUB_ENV
          else
            echo "Unsupported tag format: $TAG_NAME"
            exit 1
          fi

      - name: Build and Push cuup image
        run: |
          docker build -t $DOCKER_REGISTRY$DOCKER_REPOSITORY/n5-cuup${SUFFIX}:${VERSION} .
          docker push $DOCKER_REGISTRY$DOCKER_REPOSITORY/n5-cuup${SUFFIX}:${VERSION}

  n5-nr-ue:
    needs: n5-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract tag info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          if [[ $TAG_NAME == n6.* ]]; then
            echo "SUFFIX=-uni" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n6-}" >> $GITHUB_ENV
          elif [[ $TAG_NAME == n5.* ]]; then
            echo "SUFFIX=" >> $GITHUB_ENV
            echo "VERSION=${TAG_NAME#n5-}" >> $GITHUB_ENV
          else
            echo "Unsupported tag format: $TAG_NAME"
            exit 1
          fi

      - name: Build and Push nr-ue image
        run: |
          docker build -t $DOCKER_REGISTRY$DOCKER_REPOSITORY/n5-nr-ue${SUFFIX}:${VERSION} .
          docker push $DOCKER_REGISTRY$DOCKER_REPOSITORY/n5-nr-ue${SUFFIX}:${VERSION}
